language: php

php:
  - 5.3
  - 5.4

env:
  - MIDGARD_EXT_VERSION=ratatoskr

before_script:
  - wget https://raw.github.com/midgardproject/midgardmvc_core/master/tests/travis_midgard2.sh
  - ./travis_midgard2.sh
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script: phpunit --coverage-text

notifications:
    irc: "irc.freenode.org#midgard"
